version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: web-server
    ports:
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/cert.pem:/etc/nginx/ssl/cert.pem:ro
      - ./config/key.pem:/etc/nginx/ssl/key.pem:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
